spring :
  application :
    name : GreenWatcher

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:file:./data/test'
    username: 'test'
    password: 'qwer1234'
    hikari: # DB Connection Pool
      auto-commit: true                 # ???? ??. (default: true)
      connection-test-query: SELECT 1   # connection ??? ?? ??
      minimum-idle: 10                  # pool? ??? ?? connection ?? ??
      maximum-pool-size: 50             # pool? ???? ? ?? ?? connection ?
      pool-name: pool                   # connection pool ??
      max-lifetime: 600000
      leak-detection-threshold: 300000

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
server:
  port: 3000

jwt:
  secret: U29tZVNlY3JldEtleUhlcmUgdGhhdCBpcyBhdCBsZWFzdCAzM0J5dGVz


logging:
  level:
    org:
      springframework:
        security=DEBUG:
    root: debug